save_folder: "/app/data_saved/"
batch_size: 4
n_samples: 16

# generation
n_gen_msgs: 50
midprice_step_size: 1

num_insertions: 10
num_coolings: 50

EVENT_TYPE_i: 4
DIRECTION_i: 0
order_volume: 75

# device & data
bsz: 1
num_devices: 1

n_messages: 500
book_dim: 501
n_vol_series: 500
sample_top_n: -1

model_size: "large"
# data_dir: "data/test_set/"
data_dir: "/app/data/test_set/"
sample_all: false
stock: "GOOG"

tick_size: 100
rng_seed: 42

ckpt_path: "./app/checkpoints/denim-elevator-754_czg1ss71/"