#FROM nvcr.io/nvidia/k8s/container-toolkit:v1.19.0-rc.1
FROM nvcr.io/nvidia/jax:25.01-py3

# Create user
ARG UID
ARG MYUSER
RUN useradd -m -u $UID --create-home ${MYUSER} && \
    echo "${MYUSER}: ${MYUSER}" | chpasswd && \
    adduser ${MYUSER} sudo && \
    # mkdir -p /home/${MYUSER}/.local/bin && \
    chown -R  ${MYUSER}:${MYUSER} /home/${MYUSER}
    
# default workdir
WORKDIR /home/${MYUSER}/
COPY --chown=${MYUSER} --chmod=777 . .

# install tmux
RUN apt-get update && \
    apt-get install -y tmux && \
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    gnupg \
    libgl1 \
    p7zip-full \
    unrar \
    htop \
    graphviz \
    libcupti-dev

RUN 
# Copy requirements.txt and verify its contents
COPY --chown=${MYUSER}:${MYUSER} requirements.txt /home/${MYUSER}/lobs5/
RUN ls -l && cat requirements.txt
RUN python3 -m pip install --upgrade pip
#jaxmarl from source if needed, all the requirements
# RUN pip install -e .[algs,dev]
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu130
RUN pip uninstall -y jax jaxlib jax-plugins jax-cuda12-pjrt jax-cuda12-plugin nvidia-cusparse nvidia-cusolver nvidia-cufft nvidia-nccl-cu12 
RUN pip install -U "jax[cuda13]==0.7.2" "jaxlib[cuda13]==0.7.2" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

RUN pip install -r requirements.txt 


RUN wget https://go.dev/dl/go1.24.5.linux-amd64.tar.gz
RUN rm -rf /usr/local/go
RUN tar -C /usr/local -xzf go1.24.5.linux-amd64.tar.gz

RUN export PATH=$PATH:/usr/local/go/bin

USER ${MYUSER}

#disabling preallocation
RUN export XLA_PYTHON_CLIENT_PREALLOCATE=false
#safety measures
RUN export XLA_PYTHON_CLIENT_MEM_FRACTION=0.85
RUN export TF_FORCE_GPU_ALLOW_GROWTH=true

# Add .local/bin to PATH
RUN echo 'export PATH=$PATH:/home/duser/.local/bin' >> ~/.bashrc


# Ensure home directory is on the Python path
# ENV PYTHONPATH="/home/${MYUSER}:$PYTHONPATH"
ENV PYTHONPATH="/home/${MYUSER}"
RUN export PATH="$HOME/.local/bin:$PATH"
RUN export PATH="$HOME/.local/lib:$PATH"
# Uncomment below if you want jupyter 
# RUN pip install jupyterlab

#for secrets and debug
# ENV WANDB_API_KEY=""
# ENV WANDB_ENTITY=""
RUN git config --global --add safe.directory /home/${MYUSER}


# Probably unnecessary to configure git user, but uncomment if needed
# RUN git config --global user.email "reuben@robots.ox.ac.uk" && \
#     git config --global user.name "reuben"


# ===== Commands ===== #

#1. docker build -t georgenigm_25jan --build-arg UID=$(id -u) --build-arg MYUSER=$(whoami) -f Dockerfile_LOBS5 . 

#2. docker rmi georgenigm_25jan

#3.1. docker run -d -it --gpus '"device=5"' --name georgenigm_lobs5_viz --user $(id -u):$(id -g) --group-add 652 -p 8888:8888 -v /scratch/local/homes/80/georgenigm/LOBS5:/app -v /scratch/local/homes/80/georgenigm/LOBS5/Alphatrade:/AlphaTrade -v /homes/groups/finance/data:/home/myuser/data -v /scratch/local/homes/80/georgenigm/LOBS5/output/evalsequences:/home/myuser/data/evalsequences -e WANDB_API_KEY=74075d19681454163130e79756ce47db4dcb571f --shm-size=1g -w /app georgenigm_25jan /bin/bash 


# docker run --rm --gpus '"device=7"' --name georgenigm_lobs5_exp_5 --user $(id -u):$(id -g) --group-add 652 -v /scratch/local/homes/80/georgenigm/LOBS5:/app -v /scratch/local/homes/80/georgenigm/LOBS5/Alphatrade:/AlphaTrade -v /homes/groups/finance/data:/home/myuser/data -v /scratch/local/homes/80/georgenigm/LOBS5/output/evalsequences:/home/myuser/data/evalsequences -e WANDB_API_KEY=74075d19681454163130e79756ce47db4dcb571f --shm-size=1g -w /app georgenigm_25jan python -u run_inference.py --stock GOOG --batch_size 32 --n_sequences 2048 --n_cond_msgs 500 --test_split 0 --checkpoint_step 23 --chunk_size 5          


# docker run --rm --gpus '"device=7"' --name georgenigm_lobs5_exp_10_buy --user $(id -u):$(id -g) --group-add 652 -v /scratch/local/homes/80/georgenigm/LOBS5:/app -v /scratch/local/homes/80/georgenigm/LOBS5/Alphatrade:/AlphaTrade -v /homes/groups/finance/data:/home/myuser/data -v /scratch/local/homes/80/georgenigm/LOBS5/output/evalsequences:/home/myuser/data/evalsequences -e WANDB_API_KEY=74075d19681454163130e79756ce47db4dcb571f --shm-size=1g -w /app georgenigm_25jan python -u lob_impact/1.aggressive_scenario_s5_rnd.py --config lob_impact/1.aggressive_scenario_config.yaml







# ===== Example commands for running aggressive scenario with different directions ===== #

docker run --rm --gpus '"device=0"' --name georgenigm_lobs5_exp_10_buy --user $(id -u):$(id -g) --group-add 652 -v /scratch/local/homes/80/georgenigm/LOBS5:/app -v /scratch/local/homes/80/georgenigm/LOBS5/Alphatrade:/AlphaTrade -v /homes/groups/finance/data:/home/myuser/data -v /scratch/local/homes/80/georgenigm/LOBS5/output/evalsequences:/home/myuser/data/evalsequences -e WANDB_API_KEY=74075d19681454163130e79756ce47db4dcb571f --shm-size=1g -w /app georgenigm_25jan python -u lob_impact/1.aggressive_scenario_s5_rnd.py --config lob_impact/1.aggressive_scenario_config.yaml --n_gen_msgs 10 --direction 0

docker run --rm --gpus '"device=1"' --name georgenigm_lobs5_exp_10_sell --user $(id -u):$(id -g) --group-add 652 -v /scratch/local/homes/80/georgenigm/LOBS5:/app -v /scratch/local/homes/80/georgenigm/LOBS5/Alphatrade:/AlphaTrade -v /homes/groups/finance/data:/home/myuser/data -v /scratch/local/homes/80/georgenigm/LOBS5/output/evalsequences:/home/myuser/data/evalsequences -e WANDB_API_KEY=74075d19681454163130e79756ce47db4dcb571f --shm-size=1g -w /app georgenigm_25jan python -u lob_impact/1.aggressive_scenario_s5_rnd.py --config lob_impact/1.aggressive_scenario_config.yaml --n_gen_msgs 10 --direction 1

docker run --rm --gpus '"device=4"' --name georgenigm_lobs5_exp_25_buy --user $(id -u):$(id -g) --group-add 652 -v /scratch/local/homes/80/georgenigm/LOBS5:/app -v /scratch/local/homes/80/georgenigm/LOBS5/Alphatrade:/AlphaTrade -v /homes/groups/finance/data:/home/myuser/data -v /scratch/local/homes/80/georgenigm/LOBS5/output/evalsequences:/home/myuser/data/evalsequences -e WANDB_API_KEY=74075d19681454163130e79756ce47db4dcb571f --shm-size=1g -w /app georgenigm_25jan python -u lob_impact/1.aggressive_scenario_s5_rnd.py --config lob_impact/1.aggressive_scenario_config.yaml --n_gen_msgs 25 --direction 0

docker run --rm --gpus '"device=5"' --name georgenigm_lobs5_exp_25_sell --user $(id -u):$(id -g) --group-add 652 -v /scratch/local/homes/80/georgenigm/LOBS5:/app -v /scratch/local/homes/80/georgenigm/LOBS5/Alphatrade:/AlphaTrade -v /homes/groups/finance/data:/home/myuser/data -v /scratch/local/homes/80/georgenigm/LOBS5/output/evalsequences:/home/myuser/data/evalsequences -e WANDB_API_KEY=74075d19681454163130e79756ce47db4dcb571f --shm-size=1g -w /app georgenigm_25jan python -u lob_impact/1.aggressive_scenario_s5_rnd.py --config lob_impact/1.aggressive_scenario_config.yaml --n_gen_msgs 25 --direction 1

docker run --rm --gpus '"device=6"' --name georgenigm_lobs5_exp_50_buy --user $(id -u):$(id -g) --group-add 652 -v /scratch/local/homes/80/georgenigm/LOBS5:/app -v /scratch/local/homes/80/georgenigm/LOBS5/Alphatrade:/AlphaTrade -v /homes/groups/finance/data:/home/myuser/data -v /scratch/local/homes/80/georgenigm/LOBS5/output/evalsequences:/home/myuser/data/evalsequences -e WANDB_API_KEY=74075d19681454163130e79756ce47db4dcb571f --shm-size=1g -w /app georgenigm_25jan python -u lob_impact/1.aggressive_scenario_s5_rnd.py --config lob_impact/1.aggressive_scenario_config.yaml --n_gen_msgs 50 --direction 0

docker run --rm --gpus '"device=7"' --name georgenigm_lobs5_exp_50_sell --user $(id -u):$(id -g) --group-add 652 -v /scratch/local/homes/80/georgenigm/LOBS5:/app -v /scratch/local/homes/80/georgenigm/LOBS5/Alphatrade:/AlphaTrade -v /homes/groups/finance/data:/home/myuser/data -v /scratch/local/homes/80/georgenigm/LOBS5/output/evalsequences:/home/myuser/data/evalsequences -e WANDB_API_KEY=74075d19681454163130e79756ce47db4dcb571f --shm-size=1g -w /app georgenigm_25jan python -u lob_impact/1.aggressive_scenario_s5_rnd.py --config lob_impact/1.aggressive_scenario_config.yaml --n_gen_msgs 50 --direction 1