save_folder: "/app/data_saved/"
# batch_size: 6
# n_samples: 240
# bsz: 24

batch_size: 4
n_samples: 500
bsz: 25

# generation = historical
n_gen_msgs: 50
midprice_step_size: 1

num_insertions: 20
num_coolings: 30

EVENT_TYPE_i: 4
DIRECTION_i: 0 # 0 for buying - 1 for selling! 

order_volume: 75
order_volume_ratio: 1.00
use_relative_volume: True

n_messages: 500
book_dim: 501
n_vol_series: 500
sample_top_n: -1

model_size: "large"
# data_dir: "data/test_set/"
data_dir: "/app/data/test_set/"
sample_all: false
stock: "GOOG"

tick_size: 100
rng_seed: 42

ckpt_path: "checkpoints/denim-elevator-754_czg1ss71/"

use_sample_file: true
sample_file_path: "sample_indices_b250_bs4_ins15_cool35.json"
start_batch: 0
end_batch: 125