#!/usr/bin/env python3
"""
Standing sample-count table: how many rollouts stand behind every headline curve.

Scans results/mid_impact/mid_trajectory_<STOCK>_<beta|decay>.npz caches (no grid
access) and writes deliverables/sample_counts.md: stock x shape x model -> n
(total pooled buy+sell rollouts = <model>_cnt[0] of the message-clock stack).
Regenerate after every fleet that touches the mid-impact caches.

  python sample_count_table.py [--out ../../deliverables/sample_counts.md]
"""
import os, glob, re, argparse
import numpy as np

B = os.path.dirname(os.path.abspath(__file__))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--cache_dir', default=os.path.join(B, 'results', 'mid_impact'))
    ap.add_argument('--out', default=os.path.join(B, '..', '..', 'deliverables', 'sample_counts.md'))
    args = ap.parse_args()

    rows = {}          # (stock, shape) -> {model: n}
    models_all = []
    for f in sorted(glob.glob(os.path.join(args.cache_dir, 'mid_trajectory_*_*.npz'))):
        m = re.match(r'mid_trajectory_(\w+)_(beta|decay)\.npz', os.path.basename(f))
        if not m:
            continue
        stock, shape = m.group(1), m.group(2)
        z = np.load(f, allow_pickle=True)
        for k in z.files:
            if k.endswith('_cnt'):
                model = k[:-4]
                n = int(np.nanmax(z[k]))
                rows.setdefault((stock, shape), {})[model] = n
                if model not in models_all:
                    models_all.append(model)

    keys = sorted(rows)
    lines = ['# Sample counts behind every headline curve',
             '',
             'Auto-generated by `5_analysis/beta/sample_count_table.py` from the '
             'mid_trajectory npz caches (n = pooled buy+sell rollouts entering the '
             'Figure-6 style k-clock mean). Regenerate after every fleet.',
             '',
             '| stock | shape | ' + ' | '.join(models_all) + ' |',
             '|---|---|' + '---|' * len(models_all)]
    for (stock, shape) in keys:
        r = rows[(stock, shape)]
        lines.append(f'| {stock} | {shape} | ' +
                     ' | '.join(str(r.get(m, '—')) for m in models_all) + ' |')
    out = os.path.abspath(args.out)
    with open(out, 'w') as fh:
        fh.write('\n'.join(lines) + '\n')
    print('\n'.join(lines))
    print(f'\nSAMPLE_TABLE_DONE -> {out}')


if __name__ == '__main__':
    main()
