n_gen_msgs: 50
num_insertions: 9
num_coolings: 90
n_cond_msgs: 500
n_eval_msgs_dataset: 500
event_type: 4
direction: 0
order_volume: 485
use_relative_volume: false
order_volume_ratio: 1.0
checkpoint_step: null
chunk_size: 5
n_samples: 2048
batch_size: 64
rng_seed: 42
stock: "GOOG"
data_dir: "/home/myuser/data/processed_data/GOOG/2023_Jan"
ckpt_path: "/home/myuser/data/checkpoints/lobs5_v2/twilight-sound-77_s42sujip"
save_dir: "/home/myuser/data/evalsequences/aggressive_scenario/context_500_buy/i9_c90_mb50_v485_cntxt91%"
tick_size: 100
sample_top_n: -1
n_vol_series: 500
book_dim: 503
test_split: 0
