n_gen_msgs: 5
num_insertions: 2
num_coolings: 2
n_cond_msgs: 500
n_eval_msgs_dataset: 500
event_type: 4
direction: 0
order_volume: 75
use_relative_volume: false
order_volume_ratio: 1.0
checkpoint_step: 34158
chunk_size: 5
n_samples: 2
batch_size: 2
rng_seed: 42
stock: "GOOG"
data_dir: "/lus/lfs1aip2/projects/s5e/lob_pipeline/data/GOOG_jan2026"
ckpt_path: "/lus/lfs1aip2/projects/s5e/quant/AlphaTrade/experiments/exp_J2_muon_optimizer/checkpoints/j2731367_u5xps1po_2731367"
save_dir: "/home/s5e/georgenigm.s5e/LOBS5_11_march/data/evalsequences/smoke_test/S5-360M/GOOG"
tick_size: 100
sample_top_n: -1
n_vol_series: 500
book_dim: 503
test_split: 0
